name: Main

on:
  push:
    tags: "v[0-9]+.[0-9]+.[0-9]+"
    branches: "main"
  pull_request:
    branches: "*"

env:
  PYTHON: python

jobs:
  lint-check:
    name: Code lint check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: make prereq

      - name: Run linters
        run: make lint

  test-core:
    name: Core tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: make prereq

      - name: Run tests
        run: make test-ci V=1

  test-pipes:
    name: Pipes tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.8"

      - name: Install Elastic Pipes
        run: pip install .

      - name: Run HCP pipes tests
        run: make -C hcp test V=1

  build:
    name: Package build (${{ matrix.os }}/py-${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.13"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make prereq

      - name: Check version
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: "python3 -c 'import core; print(core.__version__)' | bash -x -c '[ \"${{ github.ref }}\" = \"refs/tags/v$(cat -)\" ]'"

      - name: Build package
        run: make package

      - name: Upload artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: python-package-${{ matrix.python-version }}-${{ matrix.os }}
          path: dist/*

  publish-test-pypi:
    name: Publish on Test PyPi
    runs-on: ubuntu-latest
    needs:
      - lint-check
      - test-core
      - test-pipes
      - build
    environment:
      name: Test PyPi
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository != 'elastic/pipes-py'

    steps:
      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.8"

      - name: Download artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: python-package-3.8-ubuntu-latest
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          print-hash: true

  publish-pypi:
    name: Publish on PyPi
    runs-on: ubuntu-latest
    needs:
      - lint-check
      - test-core
      - test-pipes
      - build
    environment:
      name: PyPi
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'elastic/pipes-py'

    steps:
      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.8"

      - name: Download artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: python-package-3.8-ubuntu-latest
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          print-hash: true
